# Generated by Django 5.2.8 on 2025-12-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.AddField(
            model_name="task",
            name="task_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
